#-mode python-
Import('env')
env = env.Clone()

test_cpps = [str(fn) for fn in Glob('*.cpp')] 

util_test_sources=  [
  '#scribe/test/dotest.cpp',
  test_cpps ]


libsname = ['rt', 'pthread', 'z','bidfeed-sharelib','event',
         'gtest', 'scribe_server', 'fb303','boost_thread','thriftnb',
          'thrift', 'scribe_common', 'boost_system']
utiltest = env.aTest(target = 'scribe_server_test',
    source = util_test_sources,
    LIBS = libsname);


