# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

############################################################
test_cpps = [str(fn) for fn in Glob('*.cc') ]

core_test_sources=  [test_cpps]

libsname = [ 'gtest',   'pthread' , 'nspio_common', 'nspio_core', 'nspio_api', 'uuid', 'bidfeed-sharelib', 'event']
commontest = env.aTest(target = 'core_test',
                       source = core_test_sources,
                       LIBS = libsname
                       );
