# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='page.proto',
  package='jungle.com.page',
  serialized_pb='\n\npage.proto\x12\x0fjungle.com.page\"r\n\x08\x43ommonID\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x0b\n\x03url\x18\x02 \x02(\t\x12\x30\n\x05\x66ield\x18\x03 \x02(\x0e\x32!.jungle.com.page.CommonID.field_t\"\x1b\n\x07\x66ield_t\x12\x08\n\x04TECH\x10\x00\x12\x06\n\x02PM\x10\x01\"\x8a\x03\n\x0eJobDescription\x12%\n\x02id\x18\x01 \x02(\x0b\x32\x19.jungle.com.page.CommonID\x12<\n\x08job_type\x18\x02 \x02(\x0e\x32*.jungle.com.page.JobDescription.job_type_t\x12\r\n\x05title\x18\x03 \x02(\t\x12\x12\n\ndepartment\x18\x04 \x02(\t\x12\x0f\n\x07require\x18\x05 \x03(\t\x12\x0c\n\x04\x64uty\x18\x06 \x03(\t\x12\x0b\n\x03\x64\x65s\x18\x07 \x02(\t\x12\r\n\x05\x61\x62out\x18\x08 \x02(\t\x12\x0e\n\x06pub_tm\x18\t \x02(\x04\x12\x11\n\texpire_tm\x18\n \x02(\x04\x12\x11\n\tupdate_tm\x18\x0b \x02(\x04\x12\x0e\n\x06salary\x18\x0c \x02(\x05\x12\x10\n\x08work_age\x18\r \x02(\x05\x12\x10\n\x08location\x18\x0e \x02(\x05\x12\x12\n\nhead_count\x18\x0f \x01(\x05\x12\x0f\n\x07\x63ontact\x18\x10 \x01(\t\"&\n\njob_type_t\x12\x0c\n\x08\x46ULLTIME\x10\x00\x12\n\n\x06INTERN\x10\x01\"\xff\x01\n\x12LectureDescription\x12%\n\x02id\x18\x01 \x02(\x0b\x32\x19.jungle.com.page.CommonID\x12@\n\x04type\x18\x02 \x02(\x0e\x32\x32.jungle.com.page.LectureDescription.lecture_type_t\x12\x0b\n\x03\x64\x65s\x18\x03 \x02(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x02(\t\x12\x0e\n\x06pub_tm\x18\x05 \x02(\x04\x12\x11\n\tupdate_tm\x18\x06 \x02(\x04\"@\n\x0electure_type_t\x12\x08\n\x04TEXT\x10\x00\x12\x07\n\x03PPT\x10\x01\x12\x07\n\x03PDF\x10\x02\x12\x07\n\x03\x44OC\x10\x03\x12\t\n\x05VIDEO\x10\x04')



_COMMONID_FIELD_T = descriptor.EnumDescriptor(
  name='field_t',
  full_name='jungle.com.page.CommonID.field_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='TECH', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PM', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=118,
  serialized_end=145,
)

_JOBDESCRIPTION_JOB_TYPE_T = descriptor.EnumDescriptor(
  name='job_type_t',
  full_name='jungle.com.page.JobDescription.job_type_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='FULLTIME', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INTERN', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=504,
  serialized_end=542,
)

_LECTUREDESCRIPTION_LECTURE_TYPE_T = descriptor.EnumDescriptor(
  name='lecture_type_t',
  full_name='jungle.com.page.LectureDescription.lecture_type_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='TEXT', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PPT', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PDF', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DOC', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VIDEO', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=736,
  serialized_end=800,
)


_COMMONID = descriptor.Descriptor(
  name='CommonID',
  full_name='jungle.com.page.CommonID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='jungle.com.page.CommonID.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='jungle.com.page.CommonID.url', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='field', full_name='jungle.com.page.CommonID.field', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMONID_FIELD_T,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=145,
)


_JOBDESCRIPTION = descriptor.Descriptor(
  name='JobDescription',
  full_name='jungle.com.page.JobDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='jungle.com.page.JobDescription.id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='job_type', full_name='jungle.com.page.JobDescription.job_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='title', full_name='jungle.com.page.JobDescription.title', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='department', full_name='jungle.com.page.JobDescription.department', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='require', full_name='jungle.com.page.JobDescription.require', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='duty', full_name='jungle.com.page.JobDescription.duty', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='des', full_name='jungle.com.page.JobDescription.des', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='about', full_name='jungle.com.page.JobDescription.about', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pub_tm', full_name='jungle.com.page.JobDescription.pub_tm', index=8,
      number=9, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='expire_tm', full_name='jungle.com.page.JobDescription.expire_tm', index=9,
      number=10, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='update_tm', full_name='jungle.com.page.JobDescription.update_tm', index=10,
      number=11, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='salary', full_name='jungle.com.page.JobDescription.salary', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='work_age', full_name='jungle.com.page.JobDescription.work_age', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='location', full_name='jungle.com.page.JobDescription.location', index=13,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='head_count', full_name='jungle.com.page.JobDescription.head_count', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='contact', full_name='jungle.com.page.JobDescription.contact', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOBDESCRIPTION_JOB_TYPE_T,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=148,
  serialized_end=542,
)


_LECTUREDESCRIPTION = descriptor.Descriptor(
  name='LectureDescription',
  full_name='jungle.com.page.LectureDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='jungle.com.page.LectureDescription.id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='jungle.com.page.LectureDescription.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='des', full_name='jungle.com.page.LectureDescription.des', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='author', full_name='jungle.com.page.LectureDescription.author', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pub_tm', full_name='jungle.com.page.LectureDescription.pub_tm', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='update_tm', full_name='jungle.com.page.LectureDescription.update_tm', index=5,
      number=6, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LECTUREDESCRIPTION_LECTURE_TYPE_T,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=545,
  serialized_end=800,
)

_COMMONID.fields_by_name['field'].enum_type = _COMMONID_FIELD_T
_COMMONID_FIELD_T.containing_type = _COMMONID;
_JOBDESCRIPTION.fields_by_name['id'].message_type = _COMMONID
_JOBDESCRIPTION.fields_by_name['job_type'].enum_type = _JOBDESCRIPTION_JOB_TYPE_T
_JOBDESCRIPTION_JOB_TYPE_T.containing_type = _JOBDESCRIPTION;
_LECTUREDESCRIPTION.fields_by_name['id'].message_type = _COMMONID
_LECTUREDESCRIPTION.fields_by_name['type'].enum_type = _LECTUREDESCRIPTION_LECTURE_TYPE_T
_LECTUREDESCRIPTION_LECTURE_TYPE_T.containing_type = _LECTUREDESCRIPTION;
DESCRIPTOR.message_types_by_name['CommonID'] = _COMMONID
DESCRIPTOR.message_types_by_name['JobDescription'] = _JOBDESCRIPTION
DESCRIPTOR.message_types_by_name['LectureDescription'] = _LECTUREDESCRIPTION

class CommonID(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMONID
  
  # @@protoc_insertion_point(class_scope:jungle.com.page.CommonID)

class JobDescription(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOBDESCRIPTION
  
  # @@protoc_insertion_point(class_scope:jungle.com.page.JobDescription)

class LectureDescription(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LECTUREDESCRIPTION
  
  # @@protoc_insertion_point(class_scope:jungle.com.page.LectureDescription)

# @@protoc_insertion_point(module_scope)
