# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

#############################################################################################################
test_cpps = [str(fn) for fn in Glob('*.cpp')]
server_test_sources=  [
    '#sharelib/test/dotest.cpp',
    test_cpps
                     ]


libsname = [ 'gtest',   'pthread' , 'z', 'sharelib_server', 'log4cpp', 'sharelib_util', 'event']
servertest = env.aTest(target = 'server_test',
                     source = server_test_sources,
                     LIBS = libsname
                     );
