#-mode python-
Import('env')
env = env.Clone()

libutil_sources = Glob('*.c[cp]*')
env.aLibrary(target = 'pluginmanager',
             source = libutil_sources,
             )

libsname = ['rt','pthread' , 'z', 'protobuf','sharelib']

env.aDirs('test')
env.aSDKIncludes(Glob('*.h'))

cpps=[libutil_sources]
Return(['cpps'] )

