#-mode python-
Import('env')
env = env.Clone()

libjson_sources = Glob('*.cpp')

libsname = ['rt']

env.aLibrary(target = 'sharelib_json',
             source = libjson_sources
             )
	
env.aSDKIncludes(Glob('*.h'))
env.aDirs('test')
Return('libjson_sources')

