#-mode python-
Import('env')
env = env.Clone()

libutil_sources = Glob('*.c[cp]*')
libsname = ['rt','pthread' , 'z','protobuf', 'log4cpp', 'boost_thread']
env.aLibrary(target = 'sharelib_util',
             source = libutil_sources,
             LIBS=[libsname]
             )


env.aDirs('test')
env.aSDKIncludes(Glob('*.h'))

cpps=[libutil_sources]
Return(['cpps'] )

