#-mode python-
Import('env')
env = env.Clone()

libspio_sources = Glob('*.cpp')

libsname = ['rt']

env.aLibrary(target = 'sharelib_spio',
             source = libspio_sources
             )
	
env.aSDKIncludes(Glob('*.h'))
env.aDirs('test')
Return('libspio_sources')

