#-mode python-
Import('env')
env = env.Clone()
   

libsname = ['rt', 'pthread', 'z', ]


libutil_sources = Glob('*.c[cp]*')
env.aLibrary(target = 'scribe_common',
             source = libutil_sources,
             LIBS=[libsname]
                          )
env.aDirs('test')
env.aSDKIncludes(Glob('*.h*'))

cpps=[libutil_sources]
Return(['cpps'] )
