# -*- mode: python -*-
import os

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

env.aDuplicate('log4cpp.conf')

