#-mode python-
Import('env')
env = env.Clone()

libcommon_sources = Glob('*.c[cp]*')
env.aLibrary(target = 'monitor_common',
             source = libcommon_sources,
             )

libsname = ['rt','pthread' , 'z','protobuf', 'log4cpp', ]

env.aDirs('test')
env.aSDKIncludes(Glob('*.h'))

cpps=[libcommon_sources]
Return(['cpps'] )

