# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

##################################################################
source_servertest=[ 'server_test_tool.cpp']
lib_servertest = env.aSharedLibrary(target = 'servertest', source = source_servertest, LIBS=['monitor_server' ])
##################################################################

test_cpps = [str(fn) for fn in Glob('*.cpp')]

server_test_sources=  [
    '#monitor/test/dotest.cpp',
    test_cpps
                     ]


libsname = [ 'gtest',   'pthread' , 'z', 'monitor_server','monitor_common', 'log4cpp', 'bidfeed-sharelib', 'servertest']
servertest = env.aTest(target = 'server_test',
                       source = server_test_sources,
                       LIBS = libsname
                       );
